// senha-vue/src/components/CaracteristicaSenha.vue
<template>
	<div class="caracteristica">
		<input
			type="checkbox"
			:checked="valor"
			class="checkbox"
			@change="
				valorMudou(($event?.target as HTMLInputElement).checked ?? false)
			"
		/>
		<span>{{ texto }}</span>
	</div>
</template>

<script setup lang="ts">
defineProps({
	texto: {
		type: String,
		required: true,
	},
	valor: {
		type: Boolean,
		required: true,
	},
});

const emit = defineEmits(["valorMudou"]);

function valorMudou(novoValor: Boolean) {
	emit("valorMudou", novoValor);
}
</script>

// senha-angular/src/app/components/caracteristica-senha.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-caracteristica-senha',
  standalone: true,
  imports: [],
  templateUrl: './caracteristica-senha.component.html',
})
export class CaracteristicaSenhaComponent {
  @Input() texto: string = '';
  @Input() valor: boolean = false;
  @Output() valorMudou = new EventEmitter<boolean>();

  alternarValor() {
    this.valor = !this.valor;
    this.valorMudou.emit(this.valor);
  }
}

<div class="caracteristica">
  <input
    type="checkbox"
    [checked]="valor"
    class="checkbox"
    (change)="alternarValor()"
  />
  <span>{{ texto }}</span>
</div>
