// senha-vue/src/components/ExibirSenha.vue
<template>
	<div class="exibir-senha">
		<p class="senha">
			<span v-if="senha">{{ senha }}</span>
			<span v-else>Selecione as opções...</span>
		</p>
		<IconCopy :size="24" class="icone" @click="copiarParaAreaTransferencia" />
	</div>
</template>

<script setup lang="ts">
import { IconCopy } from "@tabler/icons-vue";

const props = defineProps({
	senha: {
		type: String,
		required: true,
	},
});

function copiarParaAreaTransferencia() {
	navigator.clipboard.writeText(props.senha!);
	alert("Senha copiada para a área de transferência");
}
</script>

// senha-angular/src/app/components/exibir-senha.component.ts
import { Component, Input } from '@angular/core';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import { tablerCopy } from '@ng-icons/tabler-icons';

@Component({
  selector: 'app-exibir-senha',
  standalone: true,
  imports: [NgIconComponent],
  templateUrl: './exibir-senha.component.html',
  providers: [provideIcons({ tablerCopy })],
})
export class ExibirSenhaComponent {
  icone = tablerCopy;
  @Input() senha: string = '';

  copiarParaAreaTransferencia() {
    navigator.clipboard.writeText(this.senha);
    alert('Senha copiada para a área de transferência');
  }
}

<div class="exibir-senha">
  <p class="senha">
    @if (senha) { {{ senha }} } @else { Selecione as opções... }
  </p>
  <div>
    <ng-icon
      [svg="icone"]
      [size="1.5rem"]
      class="icone"
      (click)="copiarParaAreaTransferencia()"
    ></ng-icon>
  </div>
</div>
