// senha-react/src/components/ForcaSenha.tsx
export interface ForcaSenhaProps {
	nivel: 0 | 1 | 2 | 3 | 4;
}

export default function ForcaSenha(props: ForcaSenhaProps) {
	const classe = [
		props.nivel == 1 ? "fraca" : "",
		props.nivel == 2 ? "media" : "",
		props.nivel == 3 ? "media" : "",
		props.nivel == 4 ? "forte" : "",
	].join("");

	return (
		<div className="forca-senha">
			<span>Força</span>
			<div className="niveis">
				<span className="texto">
					{props.nivel === 1 ? "Fraca" : ""}
					{props.nivel === 2 ? "Média" : ""}
					{props.nivel === 3 ? "Média" : ""}
					{props.nivel === 4 ? "Forte" : ""}
				</span>
				<div className={`nivel ${classe}`}></div>
				<div className={`nivel ${props.nivel >= 2 ? classe : ""}`}></div>
				<div className={`nivel ${props.nivel >= 3 ? classe : ""}`}></div>
				<div className={`nivel ${props.nivel == 4 ? classe : ""}`}></div>
			</div>
		</div>
	);
}

// senha-angular/src/app/components/forca-senha.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-forca-senha',
  standalone: true,
  imports: [],
  templateUrl: './forca-senha.component.html',
})
export class ForcaSenhaComponent {
  @Input() nivel: 0 | 1 | 2 | 3 | 4 = 0;

  get classe() {
    return [
      this.nivel == 1 ? 'fraca' : '',
      this.nivel == 2 ? 'media' : '',
      this.nivel == 3 ? 'media' : '',
      this.nivel == 4 ? 'forte' : '',
    ].join('');
  }
}

<div class="forca-senha">
  <span>Força</span>
  <div class="niveis">
    <span class="texto">
      @if (nivel === 1) { Fraca } @else if (nivel === 2) { Média } @else if
      (nivel === 3) { Média } @else if (nivel === 4) { Forte }
    </span>
    <div class="nivel" [class]="classe"></div>
    <div class="nivel" [class]="nivel >= 2 ? classe : ''"></div>
    <div class="nivel" [class]="nivel >= 3 ? classe : ''"></div>
    <div class="nivel" [class]="nivel == 4 ? classe : ''"></div>
  </div>
</div>
