// senha-vue/src/components/TamanhoSenha.vue
<template>
	<div class="tamanho-senha">
		<div class="info">
			<span>Qtde de Caracteres</span>
			<span>{{ tamanho }}</span>
		</div>
		<div class="slider">
			<input
				type="range"
				min="4"
				max="80"
				:value="tamanho ?? 12"
				@input="tamanhoMudou(+($event.target as HTMLInputElement).value)"
			/>
		</div>
	</div>
</template>

<script setup lang="ts">
defineProps({
	tamanho: {
		type: Number,
		required: true,
	},
});
const emit = defineEmits(["tamanhoMudou"]);

function tamanhoMudou(novoTamanho: Number) {
	emit("tamanhoMudou", novoTamanho);
}
</script>

// senha-angular/src/app/components/tamanho-senha.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-tamanho-senha',
  standalone: true,
  imports: [],
  templateUrl: './tamanho-senha.component.html',
})
export class TamanhoSenhaComponent {
  @Input() tamanho: number = 8;
  @Output() tamanhoMudou = new EventEmitter<number>();

  alterarTamanho(evento: Event) {
    const elemento = evento.target as HTMLInputElement;
    this.tamanho = +elemento.value;
    this.tamanhoMudou.emit(this.tamanho);
  }
}

<div class="tamanho-senha">
    <div class="info">
      <span>Qtde de Caracteres</span>
      <span>{{ tamanho }}</span>
    </div>
    <div class="slider">
      <input
        type="range"
        min="4"
        max="80"
        [value]="tamanho"
        (input)="alterarTamanho($event)"
      />
    </div>
  </div>
