// senha-vue/src/App.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { Senha } from "regras";
import CaracteristicaSenha from "@/components/CaracteristicaSenha.vue";
import ExibirSenha from "@/components/ExibirSenha.vue";
import ForcaSenha from "@/components/ForcaSenha.vue";
import TamanhoSenha from "@/components/TamanhoSenha.vue";

const tamanho = ref(8);
const minusculas = ref(true);
const maiusculas = ref(true);
const numeros = ref(true);
const simbolos = ref(true);

const senha = computed(() => {
	return Senha.gerar({
		tamanho: tamanho.value,
		minusculas: minusculas.value,
		maiusculas: maiusculas.value,
		numeros: numeros.value,
		simbolos: simbolos.value,
	});
});
</script>

<template>
	<main class="tela">
		<div className="conteudo">
			<h1 className="titulo">Gerador de Senha - Vue</h1>
			<ExibirSenha :senha="senha" />
			<div className="formulario">
				<TamanhoSenha :tamanho="tamanho" @tamanhoMudou="tamanho = $event" />
				<div className="caracteristicas-senha">
					<CaracteristicaSenha
						texto="Incluir Letras Minúsculas"
						:valor="minusculas"
						@valorMudou="(novoValor) => (minusculas = novoValor)"
					/>
					<CaracteristicaSenha
						texto="Incluir Letras Maiúsculas"
						:valor="maiusculas"
						@valorMudou="(novoValor) => (maiusculas = novoValor)"
					/>
					<CaracteristicaSenha
						texto="Incluir Números"
						:valor="numeros"
						@valorMudou="(novoValor) => (numeros = novoValor)"
					/>
					<CaracteristicaSenha
						texto="Incluir Símbolos"
						:valor="simbolos"
						@valorMudou="(novoValor) => (simbolos = novoValor)"
					/>
				</div>
				<ForcaSenha :nivel="Senha.nivel(senha)" />
			</div>
		</div>
	</main>
</template>

// senha-angular/src/app/app.component.ts
import { CaracteristicaSenhaComponent } from './components/caracteristica-senha.component';
import { Component } from '@angular/core';
import { ExibirSenhaComponent } from './components/exibir-senha.component';
import { ForcaSenhaComponent } from './components/forca-senha.component';
import { RouterOutlet } from '@angular/router';
import { Senha } from 'regras';
import { TamanhoSenhaComponent } from './components/tamanho-senha.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    RouterOutlet,
    ExibirSenhaComponent,
    CaracteristicaSenhaComponent,
    TamanhoSenhaComponent,
    ForcaSenhaComponent,
  ],
  templateUrl: './app.component.html',
})
export class AppComponent {
  tamanho: number = 8;
  maiusculas: boolean = true;
  minusculas: boolean = true;
  numeros: boolean = true;
  simbolos: boolean = true;

  get senha() {
    return Senha.gerar({
      tamanho: this.tamanho,
      maiusculas: this.maiusculas,
      minusculas: this.minusculas,
      numeros: this.numeros,
      simbolos: this.simbolos,
    });
  }

  get nivel() {
    return Senha.nivel(this.senha);
  }

  alterarTamanho(valor: number) {
    this.tamanho = valor;
  }

  alterarMaiusculas(valor: boolean) {
    this.maiusculas = valor;
  }

  alterarMinusculas(valor: boolean) {
    this.minusculas = valor;
  }

  alterarNumeros(valor: boolean) {
    this.numeros = valor;
  }

  alterarSimbolos(valor: boolean) {
    this.simbolos = valor;
  }
}

<main class="tela">
  <div class="conteudo">
    <h1 class="titulo">Gerador de Senha</h1>
    <app-exibir-senha [senha]="senha"></app-exibir-senha>
    <div class="formulario">
      <app-tamanho-senha
        [tamanho]="tamanho"
        (tamanhoMudou)="alterarTamanho($event)"
      ></app-tamanho-senha>
      <div class="caracteristicas-senha">
        <app-caracteristica-senha
          texto="Incluir Letras Minúsculas"
          [valor]="minusculas"
          (valorMudou)="alterarMinusculas($event)"
        ></app-caracteristica-senha>
        <app-caracteristica-senha
          texto="Incluir Letras Maiúsculas"
          [valor]="maiusculas"
          (valorMudou)="alterarMaiusculas($event)"
        ></app-caracteristica-senha>
        <app-caracteristica-senha
          texto="Incluir Números"
          [valor]="numeros"
          (valorMudou)="alterarNumeros($event)"
        ></app-caracteristica-senha>
        <app-caracteristica-senha
          texto="Incluir Símbolos"
          [valor]="simbolos"
          (valorMudou)="alterarSimbolos($event)"
        ></app-caracteristica-senha>
      </div>
      <app-forca-senha [nivel]="nivel"></app-forca-senha>
    </div>
  </div>
</main>
