// senha-react/src/components/CaracteristicaSenha.tsx
export interface CaracteristicaSenhaProps {
    texto: string
    valor: boolean
    valorMudou: (valor: boolean) => void
}

export default function CaracteristicaSenha(props: CaracteristicaSenhaProps) {
    return (
        <div className="caracteristica">
            <input
                type="checkbox"
                checked={props.valor}
                className="checkbox"
                onChange={(e) => props.valorMudou(e.target.checked)}
            />
            <span>{props.texto}</span>
        </div>
    )
}

// senha-vue/src/components/CaracteristicaSenha.vue
<template>
	<div class="caracteristica">
		<input
			type="checkbox"
			:checked="valor"
			class="checkbox"
			@change="
				valorMudou(($event?.target as HTMLInputElement).checked ?? false)
			"
		/>
		<span>{{ texto }}</span>
	</div>
</template>

<script setup lang="ts">
defineProps({
	texto: {
		type: String,
		required: true,
	},
	valor: {
		type: Boolean,
		required: true,
	},
});

const emit = defineEmits(["valorMudou"]);

function valorMudou(novoValor: Boolean) {
	emit("valorMudou", novoValor);
}
</script>
