// senha-react/src/components/ExibirSenha.tsx
'use client'

import { IconCopy } from '@tabler/icons-react'

export interface ExibirSenhaProps {
    senha: string
}

export default function ExibirSenha(props: ExibirSenhaProps) {
    function copiarParaAreaTransferencia() {
        navigator.clipboard.writeText(props.senha)
        alert('Senha copiada para a área de transferência')
    }

    return (
        <div className="exibir-senha">
            <p className="senha">{props.senha ? props.senha : 'Selecione as opções...'}</p>
            <div>
                <IconCopy size={24} className="icone" onClick={copiarParaAreaTransferencia} />
            </div>
        </div>
    )
}

// senha-vue/src/components/ExibirSenha.vue
<template>
	<div class="exibir-senha">
		<p class="senha">
			<span v-if="senha">{{ senha }}</span>
			<span v-else>Selecione as opções...</span>
		</p>
		<IconCopy :size="24" class="icone" @click="copiarParaAreaTransferencia" />
	</div>
</template>

<script setup lang="ts">
import { IconCopy } from "@tabler/icons-vue";

const props = defineProps({
	senha: {
		type: String,
		required: true,
	},
});

function copiarParaAreaTransferencia() {
	navigator.clipboard.writeText(props.senha!);
	alert("Senha copiada para a área de transferência");
}
</script>
