// senha-react/src/components/TamanhoSenha.tsx
'use client'

export interface TamanhoSenhaProps {
    tamanho: number
    tamanhoMudou: (tamanho: number) => void
}

export default function TamanhoSenha(props: TamanhoSenhaProps) {
    return (
        <div className="tamanho-senha">
            
            <div className="info">
                <span>Qtde de Caracteres</span>
                <span>{props.tamanho}</span>
            </div>
            
            <div className="slider">
                <input
                    type="range"
                    min="4"
                    max="80"
                    value={props.tamanho}
                    onChange={(e) => props.tamanhoMudou(Number(e.target.value))}
                />
            </div>
            
        </div>
    )
}

// senha-vue/src/components/TamanhoSenha.vue
<template>
	<div class="tamanho-senha">
		<div class="info">
			<span>Qtde de Caracteres</span>
			<span>{{ tamanho }}</span>
		</div>
		<div class="slider">
			<input
				type="range"
				min="4"
				max="80"
				:value="tamanho ?? 12"
				@input="tamanhoMudou(+($event.target as HTMLInputElement).value)"
			/>
		</div>
	</div>
</template>

<script setup lang="ts">
defineProps({
	tamanho: {
		type: Number,
		required: true,
	},
});
const emit = defineEmits(["tamanhoMudou"]);

function tamanhoMudou(novoTamanho: Number) {
	emit("tamanhoMudou", novoTamanho);
}
</script>
